- name: create directory if they don't exist
  file:
    path: "{{ item }}"
    state: directory
    owner: rifle0
    group: rifle0
    mode: 0644
  with_items:
    - /home/rifle0/mapped/var/www/vhosts
    - /home/rifle0/mapped/var/lib/mysql/
    - /home/rifle0/mapped/etc/apache2/sites-enabled/
